### ISSUE TITLE
Player submits form if contained as child element

### ISSUE THREAD

**Issue by romanzipp** [kaltura/playkit-js-ui#511]
##### Prerequisites
- [x] Have you checked for duplicate [issues](https://github.com/kaltura/playkit-js-ui/issues)
- [x] Which Plugin [version](https://github.com/kaltura/playkit-js-ui/releases) are you using: [Kaltura-Player 0.53.7](https://github.com/kaltura/kaltura-player-js/releases/tag/v0.53.7)
- [x] Can you reproduce the issue with our latest release version: yes
- [x] Can you reproduce the issue with the latest code from master: yes
- [x] What browser and OS names and versions are you using: Google Chrome 83.0.4103.61 (Official Build) @ macOS Catalina 10.15.5
- [x] If applicable, add test code or test page to reproduce: [**JSFiddle**](https://jsfiddle.net/romanzipp/he9gwf1o/)

##### Expected behavior
The player should not submit any parent forms by preventing the default `<button>` submit behavior.

##### Actual behavior
If a player instance is child of a `<form>` element, the corresponding form will be submitted when clicking on UI elements such as **play button**, **skip forwards/backwards elements** etc.

See the attached [JSFiddle](https://jsfiddle.net/romanzipp/he9gwf1o/) for reproduction.

##### Temporary workaround

```js
document.querySelectorAll('form').forEach(form => form.addEventListener('submit', e => {

    const submitter = e.submitter;

    if (!submitter) {
        return;
    }

    const parentPlaykitElement = submitter.closest('.playkit-player');

    if (!parentPlaykitElement) {
        return;
    }

    e.preventDefault();
}));
```

**Comment by kaltura-hooks** [comment]
Hi @romanzipp,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by OrenMe** [comment]
Hi @romanzipp, thanks for reporting.
Issue will be fixed in next release by https://github.com/kaltura/playkit-js-ui/pull/512.
