### ISSUE TITLE
Unable to remove SeekBarPlaybackContainer from player

### ISSUE THREAD

**Issue by jrobertojunior** [kaltura/playkit-js-ui#651]
I'm aiming to make a player without visible UI components. I found this [guide](https://github.com/kaltura/playkit-js-ui/blob/master/docs/ui-components.md) which shows that to hide a component using config.UiComponents, you'd have specify the preset, the area, the component name and finally return KalturaPlayer.ui.components.Remove.

Example:
```javascript
{
  ui: {
    uiComponents: [
      {
        presets: ['Playback', 'Live'],
        area: 'BottomBarRightControls',
        replaceComponent: 'Settings',
        get: KalturaPlayer.ui.components.Remove
      }
    ]
  }
}
```

I was able to hide all components from the bottom bar - using BottomBarLeftControls and BottomBarLeftControls areas - but I coudn't find the area in which SeekBarPlaybackContainer belongs to, making the seek bar the only component visible.

I've tried all areas specified in [this link](https://github.com/kaltura/playkit-js-ui/blob/master/docs/ui-components.md), and none of them worked. After reading the code, it seems that SeekBarPlaybackContainer doesn't belong to any area, in fact...

How can I hide the seek bar using config.UiComponents?

**Comment by kaltura-hooks** [comment]
Hi @jrobertojunior,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by yairans** [comment]
@jrobertojunior seems like we have a regression. in past `SeekBarPlaybackContainer` was in `BottomeBar` area. thanks for letting us know about it. 
anyway, the simplest way to make a player without visible UI components is by the following configuration: 
```
config: {
  ui: {
    disable: true
  }
}
```

**Comment by jrobertojunior** [comment]
Thank you for your reply.

Is there an way to disable all UI and still be able to play/pause video when clicking on it?

**Comment by jrobertojunior** [comment]
That did the trick. I'm closing this issue, thank you!
